name: Update Website
on:
  push:
    branches: main

jobs:
  update:
    runs-on: ubuntu-latest
    name: Update Website
    steps:
      - name: Trigger Website Redeploy
        env:
          WORKFLOW_TOKEN: ${{ secrets.WORKFLOW_TOKEN }}
        run: |
          curl \
            -X POST \
            -d '{"ref": "main"}' \
            "https://x-access-token:${WORKFLOW_TOKEN}@api.github.com/repos/PsychoLlama/website/actions/workflows/deploy.yml/dispatches"
